sudo: required

language: bash
script:
  - make deb
  - echo "ALL check"
  - ls *
  - echo "bundles check"
  - ls bundles/

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git-all build-essential 


deploy:
  provider: releases
  file_glob: true
  api_key: $GITHUB_OAUTH_TOKEN
  file: bundles/*
  skip_cleanup: true
  draft: true
